const nodesInfoConfig = {
  'business.Category': {
    name: '业务目录',
    value: 'business.Category',
    icon: 'g-job',
    color: '#999999',
    backgroundColor: '#0DC2F7',
    textColor: '#0DC2F7',
    label: 'm',
    expandRelations: {
      获取推荐拓展关系列表: 'getRecommendExpandNodes',
      所有: 'ALL',
      其他关系: 'OTHERS',
      上游父子关系: 'LAST_PARENT_CHILD',
      下游父子关系: 'NEXT_PARENT_CHILD',
    },
  },
  'business.LogicEntity': {
    name: '逻辑实体',
    value: 'business.LogicEntity',
    icon: 'g-logic-entity',
    color: '#0099CC',
    backgroundColor: '#B21EFF',
    textColor: '#B21EFF',
    label: 'L',
    expandRelations: {
      获取推荐拓展关系列表: 'getRecommendExpandNodes',
      所有: 'ALL',
      推荐关系: 'RECOMMEND',
      逻辑物理关系: 'LOGICAL_PHYSICAL',
      上游父子关系: 'LAST_PARENT_CHILD',
      其他关系: 'OTHERS',
      下游父子关系: 'NEXT_PARENT_CHILD',
    },
  },
  'business.LogicEntityField': {
    name: '业务属性',
    value: 'business.LogicEntityField',
    icon: 'g-logic-entity-column',
    color: '#99CCFF',
    backgroundColor: '#B21EFF',
    textColor: '#B21EFF',
    label: 's',
    expandRelations: {
      获取推荐拓展关系列表: 'getRecommendExpandNodes',
      所有: 'ALL',
      推荐关系: 'RECOMMEND',
      上游父子关系: 'LAST_PARENT_CHILD',
      其他关系: 'OTHERS',
      逻辑物理关系: 'LOGICAL_PHYSICAL',
    },
  },
  'dli.View': {
    name: '概览',
    value: 'dli.View',
    icon: 'g-default',
    color: '#777777',
    backgroundColor: '#2C41FF',
    textColor: '#2C41FF',
    label: 'V',
    expandRelations: {
      获取推荐拓展关系列表: 'getRecommendExpandNodes',
      所有: 'ALL',
      推荐关系: 'RECOMMEND',
    },
  },
  'dlf.dli_sql': {
    name: 'dli_sql',
    value: 'dlf.dli_sql',
    icon: 'g-job',
    color: '#339933',
    backgroundColor: '#0DC2F7',
    textColor: '#0DC2F7',
    label: 'j',
    expandRelations: {
      获取推荐拓展关系列表: 'getRecommendExpandNodes',
      所有: 'ALL',
      推荐关系: 'RECOMMEND',
    },
  },
  'dii.InsightNode': {
    name: 'dli_sql',
    value: 'dii.InsightNode',
    icon: 'g-insight',
    color: '#c2e5a0',
    backgroundColor: '#0DC2F7',
    textColor: '#0DC2F7',
    label: 'I',
    expandRelations: {
      获取推荐拓展关系列表: 'getRecommendExpandNodes',
      所有: 'ALL',
      推荐关系: 'RECOMMEND',
    },
  },
  'business.Insight': {
    name: 'dli_sql',
    value: 'business.Insight',
    icon: 'g-insight',
    color: '#FF6666',
    backgroundColor: '#0DC2F7',
    textColor: '#0DC2F7',
    label: 'i',
    expandRelations: {
      获取推荐拓展关系列表: 'getRecommendExpandNodes',
      所有: 'ALL',
      推荐关系: 'RECOMMEND',
    },
  },
  'dli.Database': {
    name: '数据库',
    value: 'dli.Database',
    icon: 'g-database',
    color: '#888888',
    backgroundColor: '#FF9800',
    textColor: '#FF9800',
    label: 'd',
    expandRelations: {
      获取推荐拓展关系列表: 'getRecommendExpandNodes',
      所有: 'ALL',
      其他关系: 'OTHERS',
      下游父子关系: 'NEXT_PARENT_CHILD',
    },
  },
  'dli.Table': {
    name: '数据表',
    value: 'dli.Table',
    icon: 'g-table',
    color: '#FF9900',
    backgroundColor: '#2C41FF',
    textColor: '#2C41FF',
    label: 'T',
    expandRelations: {
      获取推荐拓展关系列表: 'getRecommendExpandNodes',
      所有: 'ALL',
      推荐关系: 'RECOMMEND',
      数据流关系: 'DATA_FLOW',
      主外键关系: 'PK_FK',
      上游父子关系: 'LAST_PARENT_CHILD',
      其他关系: 'OTHERS',
      逻辑物理关系: 'LOGICAL_PHYSICAL',
      下游父子关系: 'NEXT_PARENT_CHILD',
    },
  },
  'dli.Column': {
    name: '字段',
    value: 'dli.Column',
    icon: 'g-column',
    color: '#FFCC33',
    backgroundColor: '#2C41FF',
    textColor: '#2C41FF',
    label: 'z',
    expandRelations: {
      获取推荐拓展关系列表: 'getRecommendExpandNodes',
      所有: 'ALL',
      推荐关系: 'RECOMMEND',
      上游父子关系: 'LAST_PARENT_CHILD',
      其他关系: 'OTHERS',
      逻辑物理关系: 'LOGICAL_PHYSICAL',
      主外键关系: 'PK_FK',
    },
  },
  'dlf.Job': {
    name: '作业',
    value: 'dlf.Job',
    icon: 'g-job',
    color: '#AAAAAA',
    backgroundColor: '#0DC2F7',
    textColor: '#0DC2F7',
    label: 'J',
    expandRelations: {
      获取推荐拓展关系列表: 'getRecommendExpandNodes',
      所有: 'ALL',
      其他关系: 'OTHERS',
      下游父子关系: 'NEXT_PARENT_CHILD',
    },
  },
  'dlf.sub_node': {
    name: '作业节点',
    value: 'dlf.sub_node',
    icon: 'g-job',
    color: '#339933',
    backgroundColor: '#0DC2F7',
    textColor: '#0DC2F7',
    label: 'j',
    expandRelations: {
      获取推荐拓展关系列表: 'getRecommendExpandNodes',
      所有: 'ALL',
      推荐关系: 'RECOMMEND',
      数据流关系: 'DATA_FLOW',
      上游父子关系: 'LAST_PARENT_CHILD',
      其他关系: 'OTHERS',
      下游父子关系: 'NEXT_PARENT_CHILD',
    },
  },
  'process.columnLineage': {
    name: '字段作业节点',
    value: 'process.columnLineage',
    icon: 'g-column-lineage',
    color: '#99CC99',
    backgroundColor: '#0DC2F7',
    textColor: '#0DC2F7',
    label: 'c',
    expandRelations: {
      获取推荐拓展关系列表: 'getRecommendExpandNodes',
      所有: 'ALL',
      推荐关系: 'RECOMMEND',
      数据流关系: 'DATA_FLOW',
      上游父子关系: 'LAST_PARENT_CHILD',
    },
  },
};

const edgesInfoConfig = {
  PARENT_CHILD: {
    name: '父子',
    value: 'PARENT_CHILD',
    // color: '#9e79db',
    color: '#888888',
    expandRelations: [],
  },
  LOGICAL_PHYSICAL: {
    name: '逻辑-物理',
    value: 'LOGICAL_PHYSICAL',
    // color: '#8dd3c7',
    color: '#888888',
    expandRelations: [],
  },
  DATA_FLOW: {
    name: '数据流',
    value: 'DATA_FLOW',
    // color: '#009966',
    color: '#888888',
    expandRelations: [],
  },
  PK_FK: {
    name: '主外键',
    value: 'PK_FK',
    // color: '#006633',
    color: '#888888',
    expandRelations: [],
  },
};

export { nodesInfoConfig, edgesInfoConfig };
